[package]
name = "unienc_webcodecs"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror = { workspace = true }
unienc_common = { workspace = true }
bincode = { workspace = true }
futures = "0.3.31"
muxide = "0.1.4"
